### ISSUE TITLE
Update js dist file header to indicate that changes have been made

### ISSUE THREAD

**Issue by jensen-cochran** [tlanclos/angular-material-keyboard#1]
- Add Taylor Lanclos as an additional author
- Change the link from https://github.com/davidenke/angular-material-keyboard to https://github.com/tlanclos/angular-material-keyboard. 

- Add the following note:

NOTE: This project was originally forked from https://github.com/davidenke/angular-material-keyboard. Additional changes have been made since the last official release on the original repo.  The changelog below is from the original repo and does not reflect the changes that have been made since then.

**Comment by tlanclos** [comment]
Fixed in latest distribution version 0.12
* updated on commit 06a7f7fb055def86d3589c520221fb3cbbe65261
